version: '3.8'

services:

  # FastAPI web application service
  web:
    build: ./project
    network_mode: host  # Use host network mode to access physical network
    command: sh -c "mkdir -p /usr/src/app/logs && chmod -R 777 /usr/src/app/data && uvicorn main:app --host 0.0.0.0 --reload"  # Ensure logs dir, fix permissions, then start FastAPI
    volumes:
      - ./project:/usr/src/app  # Mount project source code for live reload
      - ./project/data:/usr/src/app/data  # Mount data directory for persistent SQLite storage
    environment:
      - CELERY_BROKER_URL=redis://localhost:6379/0  # Celery broker URL for task queue (localhost in host mode)
      - CELERY_RESULT_BACKEND=redis://localhost:6379/0  # Celery result backend
    depends_on:
      - redis  # Ensure Redis is started before web
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Allow access to host network
    user: "0:0"

  # Celery worker service for background task processing
  worker:
    build: ./project
    network_mode: host
    command: sh -c "mkdir -p /usr/src/app/logs && chmod -R 777 /usr/src/app/data && celery -A worker.celery worker --loglevel=info --logfile=logs/celery.log --concurrency=4 --hostname=worker@%h"
    volumes:
      - ./project:/usr/src/app
      - ./project/data:/usr/src/app/data
    environment:
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - CELERY_RESULT_BACKEND=redis://localhost:6379/0
      - TZ=Europe/London
    depends_on:
      - web
      - redis
    cap_add:
      - NET_ADMIN
      - NET_RAW
    user: "0:0"

  # Flower dashboard for monitoring Celery tasks
  dashboard:
    build: ./project
    network_mode: host
    command: sh -c "mkdir -p /usr/src/app/logs && celery --broker=redis://localhost:6379/0 flower --port=5555 --log-file=logs/flower.log"  # Ensure logs dir, then start Flower and log to logs/flower.log
    environment:
      - CELERY_BROKER_URL=redis://localhost:6379/0  # Celery broker URL
      - CELERY_RESULT_BACKEND=redis://localhost:6379/0  # Celery result backend
    depends_on:
      - web     # Wait for web service
      - redis   # Wait for Redis
      - worker  # Wait for worker
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Allow access to host network
    volumes:
      - ./project/logs:/usr/src/app/logs

  # Streamlit UI for device dashboard
  streamlit:
    build: ./dashboard
    network_mode: host
    volumes:
      - ./dashboard:/app
    depends_on:
      - web

  # Redis service for Celery broker and backend
  redis:
    image: redis:7  # Use official Redis image
    network_mode: host